config/routes.rb
Rails.application.routes.draw do
  get 'top/index'
  get 'top/contact'
  root "top#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:content => "width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0", :name => "viewport"}/
    %title Portfolio
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/top/_body.html.haml
.body
  .body__container1
    .body__container1__center
      .body__container1__center__upper
      .body__container1__center__profile
        .body__container1__center__profile__comment
          %p 人の想いをインターネットを
          %p 通じ表現する、想いを届ける
          %p お手伝いが出来ればと
          %p 考えています
          %a
        .body__container1__center__profile__image
          = image_tag "profile.1.jpg", height: '400px', width: '400px'
  .body__container2#profile
    .body__container2__theme
      Profile
    .body__container2__box
      .body__container2__box__1
        %c 都内のアパレル店員を経て30才目前にして
        %br オーストラリアへ
        %a 帰国後に地元和歌山で
        %p 建材メーカーの営業として勤務する
        %c 地元の懐かしい空気に癒されるも
        %br 仕事では人生で一番の挫折を味わい一念発起
        %a 都内のプログラミングスクールに通い、
        %p 人の想いを繋げるWEBクリエーターを目指す
  .body__container3#skill
    .body__container3__theme
      Skill
    .body__container3__box
      .body__container3__box__1
        %h2 Design
        = image_tag "photoshop-cc.svg", size: '50x50'
        = image_tag "lightroom-cc.svg", size: '50x50'
        = image_tag "adobe-illustrator-cc.svg", size: '50x50'
      .body__container3__box__2
        %h2 Frontend
        %i.fab.fa-html5
        %i.fab.fa-css3-alt
        %i.fab.fa-js
      .body__container3__box__3
        %h2 Backend
        %i.fas.fa-gem
        %h2 Server
        %i.fab.fa-aws
  .body__container4#works
    .body__container4__theme
      Works
    .body__container4__box
      .body__container4__box__1
        = link_to "http://54.92.79.192/" do
          = image_tag "gifts-space.png", class: 'works'
      .body__container4__box__2
        = link_to 'http://18.176.21.46' do
          = image_tag "chat-space.png", class: 'works'
      .body__container4__box__3
        = link_to 'http://52.192.4.46/' do
          = image_tag "Fmarket.png", class: 'works'
  .body__container5#contact
    .body__container5__theme
      Contact
    .body__container5__box
      .body__container5__box__1
        %c ご依頼は下記お問い合わせまで
        %br よろしくお願いいたします！
      .body__container5__box__2
        = link_to top_contact_path do
          %i.fas.fa-envelope

app/views/top/_footer.html.haml
.footer
  .footer__container1
    .footer__container1__sns
      = link_to "https://twitter.com/hiro0forest" do
        %i.fab.fa-twitter-square
      = link_to "https://github.com/hiro-forest" do
        %i.fab.fa-github-square
  .footer__container2
    © 2020 Hiroki Morimoto

app/views/top/_footer2.html.haml
.footer2
  .footer__container1
    .footer__container1__sns
      = link_to "https://twitter.com/hiro0forest" do
        %i.fab.fa-twitter-square
      = link_to "https://github.com/hiro-forest" do
        %i.fab.fa-github-square
  .footer__container2
    © 2020 Hiroki Morimoto

app/views/top/_form.html.haml
.form
  .form__box
    %iframe{ src: "https://docs.google.com/forms/d/e/1FAIpQLSdR74SrqERMpLNVa5xzh4U_l4ZoV0vBFqc0GQxweA2jXJP9vg/viewform?embedded=true", frameborder: "0",　marginheight: "0",　marginwidth: "0", height: "100%", width: "100%"} 読み込んでいます…

app/views/top/_header.html.haml
.header
  .header__main
    .header__main__name
      Hiroki Morimoto
    .header__main__box
      = link_to "Profile", "#profile", class: 'menu'
      = link_to "Skill", "#skill", class: 'menu'
      = link_to "Works", "#works", class: 'menu'
      = link_to "Contact", "#contact", class: 'menu'

app/views/top/_header2.html.haml
.header2
  .header__main
    .header__main__name
      Hiroki Morimoto
      = link_to root_path do
        %i.fas.fa-undo-alt
    .header__main__box

app/views/top/contact.html.haml
.wrapper
  = render "header2"
  = render "form"
  = render "footer2"

app/views/top/index.html.haml
.wrapper
  = render "header"
  = render "body"
  = render "footer"